### ISSUE TITLE
How do you get the recorded data off of the device if SD card is soldered?

### ISSUE THREAD

**Issue by slavik0329** [pigetArduino/gpsLogger#3]
How do you get the recorded data off of the device if SD card is soldered?

**Comment by remisarrailh** [comment]
I realize I wasn't really clear about it, I solder a micro-sd card adapter not an sdcard.
I should probably update the doc to reflect this better.

**Comment by slavik0329** [comment]
@maditnerd Yea, there is nothing in the docs at all about this. Thank you !
